"""empty message

Revision ID: 15ac1949356b
Revises: 
Create Date: 2024-11-10 17:11:21.036731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15ac1949356b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteries',
    sa.Column('pot', sa.Integer(), nullable=False),
    sa.Column('tickets', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('last_ticket_index', sa.Integer(), nullable=False),
    sa.Column('jackpot', sa.Integer(), nullable=True),
    sa.Column('draw_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotteries_created_at'), 'lotteries', ['created_at'], unique=False)
    op.create_index(op.f('ix_lotteries_updated_at'), 'lotteries', ['updated_at'], unique=False)
    op.create_table('secret_codes',
    sa.Column('key', sa.Date(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'secret', name='secret_codes_key_secret_unx')
    )
    op.create_index(op.f('ix_secret_codes_created_at'), 'secret_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_secret_codes_key'), 'secret_codes', ['key'], unique=False)
    op.create_index(op.f('ix_secret_codes_updated_at'), 'secret_codes', ['updated_at'], unique=False)
    op.create_table('system',
    sa.Column('last_user_log', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_user_cumulative', sa.Integer(), nullable=True),
    sa.Column('last_action_log', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_created_at'), 'system', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_updated_at'), 'system', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('invited_users', sa.Integer(), nullable=False),
    sa.Column('joined', sa.Boolean(), nullable=False),
    sa.Column('referrer_id', sa.BigInteger(), nullable=True),
    sa.Column('join_reward', sa.Boolean(), nullable=False),
    sa.Column('last_check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_lucky_push', sa.DateTime(timezone=True), nullable=False),
    sa.Column('push_points', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('push_count', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('custom_lang', sa.String(), nullable=False),
    sa.Column('static_rank', sa.Integer(), nullable=False),
    sa.Column('last_secret_code_date', sa.DATE(), nullable=False),
    sa.Column('total_ads_watched', sa.Integer(), nullable=False),
    sa.Column('total_ads_watched_this_push', sa.Integer(), nullable=False),
    sa.Column('last_ads_watch_for_points', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_ads_watched_for_points', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(), nullable=True),
    sa.Column('tasks_join_channel', sa.Enum('NOT_DONE', 'DONE', 'CLAIMED', name='taskstatus'), nullable=False),
    sa.Column('tasks_active_tickets', sa.Enum('NOT_DONE', 'DONE', 'CLAIMED', name='taskstatus'), nullable=False),
    sa.Column('tasks_refer_a_friend', sa.Enum('NOT_DONE', 'DONE', 'CLAIMED', name='taskstatus'), nullable=False),
    sa.Column('tasks_secret_code', sa.Enum('NOT_DONE', 'DONE', 'CLAIMED', name='taskstatus'), nullable=False),
    sa.Column('tasks_watch_ads', sa.Enum('NOT_DONE', 'DONE', 'CLAIMED', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_points'), 'users', ['points'], unique=False)
    op.create_index(op.f('ix_users_src'), 'users', ['src'], unique=False)
    op.create_index(op.f('ix_users_static_rank'), 'users', ['static_rank'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table('participants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('activate_tickets_count', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'user_id', name='participants_lottery_user_unx')
    )
    op.create_index(op.f('ix_participants_created_at'), 'participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_participants_updated_at'), 'participants', ['updated_at'], unique=False)
    op.create_table('system_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('tag', sa.Enum('PUSH', 'SECRET', 'SCRATCH', 'ADS_DOUBLE', 'ADS_POINT', 'CLAIM', name='logtag'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_updated_at'), 'system_logs', ['updated_at'], unique=False)
    op.create_table('tickets',
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_index', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('matched', sa.Integer(), nullable=False),
    sa.Column('win', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'ticket_index', name='tickets_lottery_index_unx'),
    sa.UniqueConstraint('lottery_id', 'ticket_number', name='tickets_lottery_number_unx')
    )
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_updated_at'), 'tickets', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
