"""empty message

Revision ID: 0d88cc701d7b
Revises: 0f52899270ae
Create Date: 2024-09-23 14:13:13.424609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0d88cc701d7b'
down_revision: Union[str, None] = '0f52899270ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_logs', sa.Column('tag', sa.Enum('PUSH', 'SECRET', 'SCRATCH', 'ADS_DOUBLE', 'ADS_POINT', name='logtag'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_logs', 'tag')
    # ### end Alembic commands ###
