"""empty message

Revision ID: 0f52899270ae
Revises: 4b0ca922ea8f
Create Date: 2024-09-23 13:57:27.435951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0f52899270ae'
down_revision: Union[str, None] = '4b0ca922ea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    #create enum LogTag
    logtag = sa.Enum('PUSH', 'SECRET', 'SCRATCH', 'ADS_DOUBLE', 'ADS_POINT', name='logtag')
    logtag.create(op.get_bind())


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_logs', 'tag')
    # ### end Alembic commands ###
