"""empty message

Revision ID: 15ac1949356b
Revises: a178dfd24a6c
Create Date: 2024-10-25 13:55:32.603626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '15ac1949356b'
down_revision: Union[str, None] = 'a178dfd24a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('custom_lang', sa.String(), nullable=True))

    # update set as language
    op.execute("UPDATE users SET custom_lang = language")

    op.alter_column('users', 'custom_lang', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
