"""empty message

Revision ID: 1c67ac6a450e
Revises: 40eccc01c0f8
Create Date: 2024-05-23 11:49:38.732900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1c67ac6a450e'
down_revision: Union[str, None] = '40eccc01c0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('last_user_log', sa.DateTime(), nullable=True),
    sa.Column('max_user_cumulative', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_created_at'), 'system', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_updated_at'), 'system', ['updated_at'], unique=False)
    op.add_column('users', sa.Column('referrer_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'])

    # set referrer_id to invited_by_id
    op.execute("UPDATE users SET referrer_id = invited_by_id")

    op.drop_column('users', 'invited_by_id')


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invited_by_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.execute("UPDATE users SET invited_by_id = referrer_id")
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    op.drop_index(op.f('ix_system_updated_at'), table_name='system')
    op.drop_index(op.f('ix_system_created_at'), table_name='system')
    op.drop_table('system')
    # ### end Alembic commands ###
