"""empty message

Revision ID: 1e84aa27ce08
Revises: 7bdb9c1a76dc
Create Date: 2024-06-22 18:11:32.018820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '1e84aa27ce08'
down_revision: Union[str, None] = '7bdb9c1a76dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_secret_code_date', sa.DATE(), nullable=True))

    op.execute("UPDATE users SET last_secret_code_date = '2021-01-01'")

    op.alter_column('users', 'last_secret_code_date', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_secret_code_date')
    # ### end Alembic commands ###
