"""empty message

Revision ID: 23ec193e4b26
Revises: a6db7426d35a
Create Date: 2024-06-01 14:42:49.216568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '23ec193e4b26'
down_revision: Union[str, None] = 'a6db7426d35a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('last_action_log', sa.DateTime(timezone=True), nullable=True))

    # update last_action_log to 1 year ago
    op.execute("UPDATE system SET last_action_log = now() - interval '1 year'")

    #set last_action_log to not null
    op.alter_column('system', 'last_action_log', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'last_action_log')
    # ### end Alembic commands ###
