"""empty message

Revision ID: 6b3e5b36ccfe
Revises: fc552093fdc7
Create Date: 2024-11-10 17:16:01.464016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6b3e5b36ccfe'
down_revision: Union[str, None] = 'fc552093fdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
