"""empty message

Revision ID: 3645dc275095
Revises: d2155502d22b
Create Date: 2024-07-23 13:51:01.574452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '3645dc275095'
down_revision: Union[str, None] = 'd2155502d22b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_count', sa.Integer(), nullable=True))

    # set push_count to push_points / 250
    op.execute("UPDATE users SET push_count = push_points / 250")

    # set not null constraint
    op.alter_column('users', 'push_count', existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'push_count')
    # ### end Alembic commands ###
