"""fulli

Revision ID: 40eccc01c0f8
Revises: 786f2cbb4fb0
Create Date: 2024-05-15 16:50:58.480736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '40eccc01c0f8'
down_revision: Union[str, None] = '786f2cbb4fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('joined', sa.Boolean(), nullable=True))


    op.execute("UPDATE users SET joined='f' WHERE joined IS NULL")
    op.alter_column('users', 'joined', nullable=False)

    op.execute("UPDATE users SET first_name='test' WHERE first_name IS NULL")
    op.alter_column('users', 'first_name', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joined')
    op.drop_column('users', 'username')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
