"""empty message

Revision ID: 4b0ca922ea8f
Revises: e0160b52d887
Create Date: 2024-09-08 14:38:25.358764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4b0ca922ea8f'
down_revision: Union[str, None] = 'e0160b52d887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('src', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_src'), 'users', ['src'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_src'), table_name='users')
    op.drop_column('users', 'src')
    # ### end Alembic commands ###
