"""empty message

Revision ID: 4de495c779c8
Revises: 23ec193e4b26
Create Date: 2024-06-06 20:13:27.820381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '4de495c779c8'
down_revision: Union[str, None] = '23ec193e4b26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_points', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=True))

    # set push_points to lucky_points * 1000
    op.execute("UPDATE users SET push_points = lucky_points * 1000")

    # set points to invited_users * 1000 + push_points
    op.execute("UPDATE users SET points = invited_users * 1000 + push_points")

    # set points and push_points to not nullable
    op.alter_column('users', 'points', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('users', 'push_points', existing_type=sa.INTEGER(), nullable=False)
    
    op.create_index(op.f('ix_users_points'), 'users', ['points'], unique=False)
    op.drop_column('users', 'lucky_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lucky_points', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_points'), table_name='users')
    op.drop_column('users', 'points')
    op.drop_column('users', 'push_points')
    # ### end Alembic commands ###
