"""empty message

Revision ID: 4f8600937ea8
Revises: 1e84aa27ce08
Create Date: 2024-06-27 14:43:46.204958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f8600937ea8'
down_revision: Union[str, None] = '1e84aa27ce08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotteries',
    sa.Column('pot', sa.Integer(), nullable=False),
    sa.Column('tickets', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('last_ticket_index', sa.Integer(), nullable=False),
    sa.Column('jackpot', sa.Integer(), nullable=True),
    sa.Column('draw_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lotteries_created_at'), 'lotteries', ['created_at'], unique=False)
    op.create_index(op.f('ix_lotteries_updated_at'), 'lotteries', ['updated_at'], unique=False)
    op.create_table('participants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('activate_tickets_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'user_id', name='participants_lottery_user_unx')
    )
    op.create_index(op.f('ix_participants_created_at'), 'participants', ['created_at'], unique=False)
    op.create_index(op.f('ix_participants_updated_at'), 'participants', ['updated_at'], unique=False)
    op.create_table('tickets',
    sa.Column('lottery_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_index', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lottery_id'], ['lotteries.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lottery_id', 'ticket_index', name='tickets_lottery_index_unx'),
    sa.UniqueConstraint('lottery_id', 'ticket_number', name='tickets_lottery_number_unx')
    )
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_updated_at'), 'tickets', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_updated_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_participants_updated_at'), table_name='participants')
    op.drop_index(op.f('ix_participants_created_at'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_lotteries_updated_at'), table_name='lotteries')
    op.drop_index(op.f('ix_lotteries_created_at'), table_name='lotteries')
    op.drop_table('lotteries')
    # ### end Alembic commands ###
