"""empty message

Revision ID: 54566a22a84c
Revises: 6932d38ed7b0
Create Date: 2024-06-17 02:07:38.567643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '54566a22a84c'
down_revision: Union[str, None] = '6932d38ed7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_static_rank'), 'users', ['static_rank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_static_rank'), table_name='users')
    # ### end Alembic commands ###
