"""empty message

Revision ID: 62823adb3557
Revises: 4f8600937ea8
Create Date: 2024-07-07 19:20:01.613388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '62823adb3557'
down_revision: Union[str, None] = '4f8600937ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('matched', sa.Integer(), nullable=True))

    op.execute("UPDATE tickets SET matched = 0")
    op.alter_column('tickets', 'matched', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'matched')
    # ### end Alembic commands ###
