"""empty message

Revision ID: 6932d38ed7b0
Revises: c46d8dbfb502
Create Date: 2024-06-17 01:56:37.097273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '6932d38ed7b0'
down_revision: Union[str, None] = 'c46d8dbfb502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('static_rank', sa.Integer(), nullable=True))

    op.execute("UPDATE users SET static_rank = 0")

    op.alter_column('users', 'static_rank', existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'static_rank')
    # ### end Alembic commands ###
