"""empty message

Revision ID: cf8c5bf90fae
Revises: 2774fcf704b1
Create Date: 2024-11-20 17:05:21.860071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'cf8c5bf90fae'
down_revision: Union[str, None] = '2774fcf704b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add RPS game to  logtag enum
    op.execute("""ALTER TYPE logtag ADD VALUE 'RPS';""")
               
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
