"""lang

Revision ID: 786f2cbb4fb0
Revises: 99a4c0f6797d
Create Date: 2024-05-12 15:53:03.816809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '786f2cbb4fb0'
down_revision: Union[str, None] = '99a4c0f6797d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(), nullable=True))

    op.execute("UPDATE users SET language='en' WHERE language IS NULL")
    op.alter_column('users', 'language', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    # ### end Alembic commands ###
