"""empty message

Revision ID: 7bdb9c1a76dc
Revises: 54566a22a84c
Create Date: 2024-06-17 07:13:01.783677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '7bdb9c1a76dc'
down_revision: Union[str, None] = '54566a22a84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET static_rank = 1000 where static_rank is null or static_rank = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
