"""empty message

Revision ID: 93f832aebbe4
Revises: 3645dc275095
Create Date: 2024-07-23 14:39:00.602965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '93f832aebbe4'
down_revision: Union[str, None] = '3645dc275095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_ads_watched', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('total_ads_watched_this_push', sa.Integer(), nullable=True))

    op.execute("UPDATE users SET total_ads_watched = 0")
    op.execute("UPDATE users SET total_ads_watched_this_push = 0")

    op.alter_column('users', 'total_ads_watched', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column('users', 'total_ads_watched_this_push', existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_ads_watched_this_push')
    op.drop_column('users', 'total_ads_watched')
    # ### end Alembic commands ###
