"""empty message

Revision ID: a6db7426d35a
Revises: 0cc3e45c9d89
Create Date: 2024-05-30 14:07:18.957326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6db7426d35a'
down_revision: Union[str, None] = '0cc3e45c9d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_lucky_push', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('lucky_points', sa.Float(), nullable=True))
    op.alter_column('users', 'last_check_in',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    

    # update lucky_points
    op.execute("UPDATE users SET lucky_points = 0.0")
    # update last_lucky_push to 1 year ago
    op.execute("UPDATE users SET last_lucky_push = now() - interval '1 year'")

    #set lucky_points to not null
    op.alter_column('users', 'lucky_points', nullable=False)
    #set last_lucky_push to not null
    op.alter_column('users', 'last_lucky_push', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_check_in',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('users', 'lucky_points')
    op.drop_column('users', 'last_lucky_push')
    # ### end Alembic commands ###
