"""empty message

Revision ID: b47b920751b5
Revises: e68cd3ffba9e
Create Date: 2024-10-20 18:19:37.632009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b47b920751b5'
down_revision: Union[str, None] = 'e68cd3ffba9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # add CLAIM to logtag enum

    op.execute("ALTER TYPE logtag ADD VALUE 'CLAIM'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
