"""empty message

Revision ID: b9963871e2bc
Revises: 0d88cc701d7b
Create Date: 2024-10-08 17:32:40.723093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'b9963871e2bc'
down_revision: Union[str, None] = '0d88cc701d7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # rename referrer_score to tasks_join_channel
    op.execute("ALTER TABLE users RENAME COLUMN referrer_score TO tasks_join_channel")
    op.add_column('users', sa.Column('tasks_active_tickets', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tasks_refer_a_friend', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tasks_secret_code', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('tasks_watch_ads', sa.Boolean(), nullable=True))


    # update tasks_active_tickets and tasks_refer_a_friend and tasks_secret_code and tasks_watch_ads to False for all users in one query
    op.execute("UPDATE users SET tasks_active_tickets = FALSE, tasks_refer_a_friend = FALSE, tasks_secret_code = FALSE, tasks_watch_ads = FALSE")


    # make tasks_active_tickets and tasks_refer_a_friend and tasks_secret_code and tasks_watch_ads not nullable
    op.alter_column('users', 'tasks_active_tickets', existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column('users', 'tasks_refer_a_friend', existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column('users', 'tasks_secret_code', existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column('users', 'tasks_watch_ads', existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
