"""empty message

Revision ID: c46d8dbfb502
Revises: 4de495c779c8
Create Date: 2024-06-07 12:39:17.666105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'c46d8dbfb502'
down_revision: Union[str, None] = '4de495c779c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_score', sa.Boolean(), nullable=True))

    # set referrer_score to joined
    op.execute("UPDATE users SET referrer_score = joined")

    # set referrer_score to not nullable
    op.alter_column('users', 'referrer_score', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referrer_score')
    # ### end Alembic commands ###
