"""empty message

Revision ID: d2155502d22b
Revises: 62823adb3557
Create Date: 2024-07-12 18:44:19.426003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2155502d22b'
down_revision: Union[str, None] = '62823adb3557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotteries', sa.Column('name', sa.String(), nullable=True))

    op.execute("UPDATE lotteries SET name = 'First Lottery'")

    op.alter_column('lotteries', 'name', existing_type=sa.VARCHAR(), nullable=False)

    op.execute("UPDATE lotteries SET draw_date = '2024-07-07T16:00:00Z'")

    op.alter_column('lotteries', 'draw_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('lotteries', 'finish_date')
    op.add_column('participants', sa.Column('wins', sa.Integer(), nullable=True))

    op.execute("UPDATE participants SET wins = 0")

    op.alter_column('participants', 'wins',
                existing_type=sa.INTEGER(),
                nullable=False)

    op.add_column('tickets', sa.Column('win', sa.Integer(), nullable=True))
    op.execute("UPDATE tickets SET win = 0")
    op.alter_column('tickets', 'win',
                existing_type=sa.INTEGER(),
                nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'win')
    op.drop_column('participants', 'wins')
    op.add_column('lotteries', sa.Column('finish_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('lotteries', 'draw_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('lotteries', 'name')
    # ### end Alembic commands ###
