"""empty message

Revision ID: d4e25aaa7e70
Revises: 93f832aebbe4
Create Date: 2024-07-26 10:24:40.715358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd4e25aaa7e70'
down_revision: Union[str, None] = '93f832aebbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_ads_watch_for_points', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('total_ads_watched_for_points', sa.Integer(), nullable=True))

    # set default as 1 year ago
    op.execute("UPDATE users SET last_ads_watch_for_points = '2023-07-26 10:24:40.715358'")
    op.execute("UPDATE users SET total_ads_watched_for_points = 0")

    op.alter_column('users', 'last_ads_watch_for_points', existing_type=sa.DateTime(timezone=True), nullable=False)
    op.alter_column('users', 'total_ads_watched_for_points', existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_ads_watched_for_points')
    op.drop_column('users', 'last_ads_watch_for_points')
    # ### end Alembic commands ###
