"""empty message

Revision ID: df583c240825
Revises: 1c67ac6a450e
Create Date: 2024-05-23 21:31:26.187154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'df583c240825'
down_revision: Union[str, None] = '1c67ac6a450e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('command', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_updated_at'), 'system_logs', ['updated_at'], unique=False)

    # create singleton system record
    op.execute("INSERT INTO system (id, last_user_log, max_user_cumulative, created_at, updated_at) VALUES (1, '2023-02-23 11:49:38.732900', 10, NOW(), NOW())")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_updated_at'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.execute("DELETE FROM system WHERE id = 1")
    # ### end Alembic commands ###
