"""empty message

Revision ID: e0160b52d887
Revises: e2b1ee82c64f
Create Date: 2024-08-29 18:42:42.345203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e0160b52d887'
down_revision: Union[str, None] = 'e2b1ee82c64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_reward', sa.Boolean(), nullable=True))

    op.execute(
        """
        UPDATE users
        SET join_reward = false
        """
    )

    op.alter_column('users', 'join_reward', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_reward')
    # ### end Alembic commands ###
