"""empty message

Revision ID: e2b1ee82c64f
Revises: d4e25aaa7e70
Create Date: 2024-08-29 14:36:45.796660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e2b1ee82c64f'
down_revision: Union[str, None] = 'd4e25aaa7e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_codes',
    sa.Column('key', sa.Date(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'secret', name='secret_codes_key_secret_unx')
    )
    op.create_index(op.f('ix_secret_codes_created_at'), 'secret_codes', ['created_at'], unique=False)
    op.create_index(op.f('ix_secret_codes_key'), 'secret_codes', ['key'], unique=False)
    op.create_index(op.f('ix_secret_codes_updated_at'), 'secret_codes', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_codes_updated_at'), table_name='secret_codes')
    op.drop_index(op.f('ix_secret_codes_key'), table_name='secret_codes')
    op.drop_index(op.f('ix_secret_codes_created_at'), table_name='secret_codes')
    op.drop_table('secret_codes')
    # ### end Alembic commands ###
