"""empty message

Revision ID: e68cd3ffba9e
Revises: 1b2195a8fb13
Create Date: 2024-10-20 11:49:59.511784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'e68cd3ffba9e'
down_revision: Union[str, None] = '1b2195a8fb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    #rename tasks_join_channel to tasks_join_channel_old

    op.alter_column('users', 'tasks_join_channel', new_column_name='tasks_join_channel_old')


    task_status = sa.Enum('NOT_DONE', 'DONE', 'CLAIMED', name='taskstatus')

    # drop tasks_join_channel, tasks_active_tickets, tasks_refer_a_friend, tasks_secret_code, tasks_watch_ads columns
    op.drop_column('users', 'tasks_active_tickets')
    op.drop_column('users', 'tasks_refer_a_friend')
    op.drop_column('users', 'tasks_secret_code')
    op.drop_column('users', 'tasks_watch_ads')


    # create tasks_join_channel, tasks_active_tickets, tasks_refer_a_friend, tasks_secret_code, tasks_watch_ads columns

    op.add_column('users', sa.Column('tasks_join_channel', task_status, nullable=True))
    op.add_column('users', sa.Column('tasks_active_tickets', task_status, nullable=True))
    op.add_column('users', sa.Column('tasks_refer_a_friend', task_status, nullable=True))
    op.add_column('users', sa.Column('tasks_secret_code', task_status, nullable=True))
    op.add_column('users', sa.Column('tasks_watch_ads', task_status, nullable=True))

    # update tasks_join_channel, tasks_active_tickets, tasks_refer_a_friend, tasks_secret_code, tasks_watch_ads columns to NOT_DONE

    op.execute("UPDATE users SET tasks_join_channel = 'NOT_DONE'")
    op.execute("UPDATE users SET tasks_active_tickets = 'NOT_DONE'")
    op.execute("UPDATE users SET tasks_refer_a_friend = 'NOT_DONE'")
    op.execute("UPDATE users SET tasks_secret_code = 'NOT_DONE'")
    op.execute("UPDATE users SET tasks_watch_ads = 'NOT_DONE'")
    
    # update tasks_join_channel to claimed where tasks_join_channel_old is true
    op.execute("UPDATE users SET tasks_join_channel = 'CLAIMED' WHERE tasks_join_channel_old = true")


    # make tasks_join_channel, tasks_active_tickets, tasks_refer_a_friend, tasks_secret_code, tasks_watch_ads columns not nullable
    op.alter_column('users', 'tasks_join_channel', nullable=False)
    op.alter_column('users', 'tasks_active_tickets', nullable=False)
    op.alter_column('users', 'tasks_refer_a_friend', nullable=False)
    op.alter_column('users', 'tasks_secret_code', nullable=False)
    op.alter_column('users', 'tasks_watch_ads', nullable=False)


    

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
